version: "3.9"

services:
  zipkinserver:
    image: openzipkin/zipkin:latest
    #mem_limit: 700m
    #restart: always
    networks:
      - greatness
    ports:
      - "9411:9411"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  configserver:
    image: greatness/configserver:latest
    mem_limit: 700m
    #restart: always
    networks:
      - greatness
    ports:
      - "8084:8084"
    depends_on:
      - zipkinserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 11s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_SLEUTH_SAMPLER_PERCENTAGE: 1
      SPRING_ZIPKIN_BASEURL: http://zipkinserver:9411/

  eurekaserver:
    image: greatness/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8085:8085"
    depends_on:
      - configserver
      - zipkinserver
    #restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    networks:
      - greatness
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084
      SPRING_SLEUTH_SAMPLER_PERCENTAGE: 1
      SPRING_ZIPKIN_BASEURL: http://zipkinserver:9411/

  gatewayserver:
    image: greatness/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8086:8086"
    depends_on:
      - configserver
      - zipkinserver
    #restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    networks:
      - greatness
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8085/eureka/
      SPRING_SLEUTH_SAMPLER_PERCENTAGE: 1
      SPRING_ZIPKIN_BASEURL: http://zipkinserver:9411/

  accounts:
    image: greatness/accounts:latest
    mem_limit: 700m
    ports:
      - "8083:8083"
    depends_on:
      - configserver
      - eurekaserver
      - gatewayserver
      - zipkinserver
    #restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 23s
        max_attempts: 3
        window: 120s
    networks:
      - greatness
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8085/eureka/
      SPRING_SLEUTH_SAMPLER_PERCENTAGE: 1
      SPRING_ZIPKIN_BASEURL: http://zipkinserver:9411/

  loans:
    image: greatness/loans:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    depends_on:
      - configserver
      - eurekaserver
      - gatewayserver
      - zipkinserver
    #restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 23s
        max_attempts: 3
        window: 120s
    networks:
      - greatness
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8085/eureka/
      SPRING_SLEUTH_SAMPLER_PERCENTAGE: 1
      SPRING_ZIPKIN_BASEURL: http://zipkinserver:9411/

  cards:
    image: greatness/cards:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    depends_on:
      - configserver
      - eurekaserver
      - gatewayserver
      - zipkinserver
    #restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 23s
        max_attempts: 3
        window: 120s
    networks:
      - greatness
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8085/eureka/
      SPRING_SLEUTH_SAMPLER_PERCENTAGE: 1
      SPRING_ZIPKIN_BASEURL: http://zipkinserver:9411/

networks:
  greatness: