version: "3.9"

services:

  configserver:
    image: greatness/configserver:latest
    mem_limit: 700m
    #restart: always
    networks:
      - greatness
    ports:
      - "8084:8084"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 8s
        max_attempts: 3
        window: 120s

  eurekaserver:
    image: greatness/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8085:8085"
    depends_on:
      - configserver
    #restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    networks:
      - greatness
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084

  accounts:
    image: greatness/accounts:latest
    mem_limit: 700m
    ports:
      - "8083:8083"
    depends_on:
      - configserver
      - eurekaserver
    #restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    networks:
      - greatness
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8085/eureka/

  loans:
    image: greatness/loans:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    depends_on:
      - configserver
      - eurekaserver
    #restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    networks:
      - greatness
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8085/eureka/

  cards:
    image: greatness/cards:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    depends_on:
      - configserver
      - eurekaserver
    #restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    networks:
      - greatness
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8085/eureka/

networks:
  greatness: